-- truncate table hits restart identity cascade;

create table if not exists hits (
    id bigint generated by default as identity not null primary key,
    app varchar(128) not null,
    uri varchar(1024) not null,
    ip varchar(16) not null,
    timestamp timestamp
);